# details see http://muyunyun.cn/create-react-doc/#/config.yml

# Site
title: Ace's Notebook

# Menu dir
## you can also set detailed dir, such as BasicSkill/css
menu: LeetCode, MLF_MLT
## set init open menu keys
menuOpenKeys: 

# site theme
theme: crd-seed

# Github
## if you want to editing pages on github, you should config these arguments.
user: AceCooool
repo: notebook
branch: master            # the default value of branch is master
deploy_branch: gh-pages   # which branch to deploy.(default: gh-pages)
# Github
## if you want to editing pages on github, you should config these arguments.
# user:
# repo:

# Available values: en | zh-cn
language: zh-cn

inject: injectLogic/index.js